services:
  petstore1:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - services/petstore/.env
  petstore2:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - services/petstore/.env
  orders:
    build:
  load-balancer:
    image: nginx
  storage:
    image: redis
