services:
  petstore-catalog:
    image: petstore-catalog
    build:
      dockerfile: petstore-catalog.Dockerfile
    env_file:
      - services/petstore-catalog/.env
    deploy:
      replicas: 2

  petstore-orders:
    image: petstore-orders
    build:
      dockerfile: petstore-orders.Dockerfile
  load-balancer:
    image: nginx
  storage:
    image: redis
