volumes:
  petstore-redis:
  petorders-redis:

services:
  petorders1:
    image: petorders
    restart: always
    depends_on:
      - petorders-redis
      - petstore1
      - petstore2
    env_file:
      - .env
    environment:
      REDIS_URL: "redis://petorders-redis:6379/0"
    ports:
      - "5003:8000"
    build:
      context: .
      dockerfile: petstore.Dockerfile
      args:
        SERVICE: "orders"
    networks:
      - petnet
  petorders2:
    image: petorders
    restart: always
    depends_on:
      - petorders-redis
      - petstore1
      - petstore2
    env_file:
      - .env
    environment:
      REDIS_URL: "redis://petorders-redis:6379/0"
    build:
      context: .
      dockerfile: petstore.Dockerfile
      args:
        SERVICE: "orders"
    networks:
      - petnet
  petstore1:
    image: petstore
    env_file:
      - .env
    build:
      context: .
      dockerfile: petstore.Dockerfile
      args:
        SERVICE: "store"
    environment:
      REDIS_URL: "redis://petstore-redis:6379/0"
    ports:
      - "5001:8000"
    depends_on:
      - petstore-redis
    restart: always
    networks:
      - petnet
  petstore-redis:
    image: petstore-redis
    build:
      context: .
      dockerfile: redis.Dockerfile
    restart: always
    volumes:
      - petstore-redis:/data
    networks:
      - petnet
  petorders-redis:
    image: petstore-redis
    build:
      context: .
      dockerfile: redis.Dockerfile
    restart: always
    volumes:
      - petorders-redis:/data
    networks:
      - petnet
  petstore2:
    image: petstore
    restart: always
    depends_on:
      - petstore-redis
    env_file:
      - .env
    build:
      context: .
      dockerfile: petstore.Dockerfile
      args:
        SERVICE: "store"
    ports:
      - "5002:8000"
    networks:
      - petnet
    environment:
      REDIS_URL: "redis://petstore-redis:6379/1"
  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - petstore1
      - petstore2
      - petorders1
      - petorders2
    networks:
      - petnet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
networks:
  petnet:
    driver: bridge
