events {
    use epoll;
    worker_connections 128;
}

http {
    upstream petstore1 {
        server petstore1:8000;
    }
    upstream petstore2 {
        server petstore2:8000;
    }

    server {
        listen 80;

        location /pet-types1 {
            limit_except GET { deny all; }
            proxy_pass http://petstore1/pet-types;
        }
        location /pet-types2 {
            limit_except GET { deny all; }
            proxy_pass http://petstore2/pet-types;
        }
        error_log /var/log/nginx/error.log debug;
    }
}