[build-system]
build-backend = "uv_build"
requires = [ "uv-build" ]

[project]
name = "petstore"
version = "0.1.0"
description = "Pet Store API"
requires-python = ">=3.14"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.14",
]

scripts.petstore = "petstore.__main__:main"
